# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.mainTabWidget.setEnabled(True)
        self.mainTabWidget.setGeometry(QtCore.QRect(10, 10, 761, 551))
        self.mainTabWidget.setObjectName("mainTabWidget")
        self.tab_settings = QtWidgets.QWidget()
        self.tab_settings.setObjectName("tab_settings")
        self.pushButton = QtWidgets.QPushButton(self.tab_settings)
        self.pushButton.setGeometry(QtCore.QRect(630, 490, 110, 21))
        self.pushButton.setObjectName("pushButton")
        self.layoutWidget = QtWidgets.QWidget(self.tab_settings)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 170, 425, 26))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.velocityProfile = QtWidgets.QComboBox(self.layoutWidget)
        self.velocityProfile.setObjectName("velocityProfile")
        self.velocityProfile.addItem("")
        self.velocityProfile.addItem("")
        self.horizontalLayout_5.addWidget(self.velocityProfile)
        self.layoutWidget1 = QtWidgets.QWidget(self.tab_settings)
        self.layoutWidget1.setGeometry(QtCore.QRect(11, 50, 215, 23))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.fishMass = QtWidgets.QLineEdit(self.layoutWidget1)
        self.fishMass.setObjectName("fishMass")
        self.horizontalLayout.addWidget(self.fishMass)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.layoutWidget2 = QtWidgets.QWidget(self.tab_settings)
        self.layoutWidget2.setGeometry(QtCore.QRect(270, 50, 270, 23))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.waterTemperature = QtWidgets.QLineEdit(self.layoutWidget2)
        self.waterTemperature.setObjectName("waterTemperature")
        self.horizontalLayout_2.addWidget(self.waterTemperature)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        self.layoutWidget3 = QtWidgets.QWidget(self.tab_settings)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 130, 439, 26))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.swimmingCostSubmodel = QtWidgets.QComboBox(self.layoutWidget3)
        self.swimmingCostSubmodel.setObjectName("swimmingCostSubmodel")
        self.swimmingCostSubmodel.addItem("")
        self.horizontalLayout_3.addWidget(self.swimmingCostSubmodel)
        self.layoutWidget4 = QtWidgets.QWidget(self.tab_settings)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 90, 613, 27))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget4)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.focalDepth = QtWidgets.QLineEdit(self.layoutWidget4)
        self.focalDepth.setObjectName("focalDepth")
        self.horizontalLayout_4.addWidget(self.focalDepth)
        self.focalDepthMeaning = QtWidgets.QComboBox(self.layoutWidget4)
        self.focalDepthMeaning.setObjectName("focalDepthMeaning")
        self.focalDepthMeaning.addItem("")
        self.focalDepthMeaning.addItem("")
        self.horizontalLayout_4.addWidget(self.focalDepthMeaning)
        self.layoutWidget5 = QtWidgets.QWidget(self.tab_settings)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 10, 731, 33))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.driftDensityFile = QtWidgets.QLineEdit(self.layoutWidget5)
        self.driftDensityFile.setObjectName("driftDensityFile")
        self.horizontalLayout_6.addWidget(self.driftDensityFile)
        self.btnDriftDensityFile = QtWidgets.QPushButton(self.layoutWidget5)
        self.btnDriftDensityFile.setObjectName("btnDriftDensityFile")
        self.horizontalLayout_6.addWidget(self.btnDriftDensityFile)
        self.mainTabWidget.addTab(self.tab_settings, "")
        self.tab_results = QtWidgets.QWidget()
        self.tab_results.setObjectName("tab_results")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_results)
        self.graphicsView.setGeometry(QtCore.QRect(265, 161, 481, 341))
        self.graphicsView.setObjectName("graphicsView")
        self.mainTabWidget.addTab(self.tab_results, "")
        self.tab_batch = QtWidgets.QWidget()
        self.tab_batch.setObjectName("tab_batch")
        self.layoutWidget6 = QtWidgets.QWidget(self.tab_batch)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 10, 731, 33))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.depthVelocityFile = QtWidgets.QLineEdit(self.layoutWidget6)
        self.depthVelocityFile.setObjectName("depthVelocityFile")
        self.horizontalLayout_7.addWidget(self.depthVelocityFile)
        self.btnDepthVelocityFile = QtWidgets.QPushButton(self.layoutWidget6)
        self.btnDepthVelocityFile.setObjectName("btnDepthVelocityFile")
        self.horizontalLayout_7.addWidget(self.btnDepthVelocityFile)
        self.mainTabWidget.addTab(self.tab_batch, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuDrift_Foraging_Habitat_Suitability = QtWidgets.QMenu(self.menubar)
        self.menuDrift_Foraging_Habitat_Suitability.setObjectName("menuDrift_Foraging_Habitat_Suitability")
        self.menuMenu_Option_2 = QtWidgets.QMenu(self.menubar)
        self.menuMenu_Option_2.setObjectName("menuMenu_Option_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFile = QtWidgets.QAction(MainWindow)
        self.actionFile.setObjectName("actionFile")
        self.actionLoad_File = QtWidgets.QAction(MainWindow)
        self.actionLoad_File.setObjectName("actionLoad_File")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuDrift_Foraging_Habitat_Suitability.addAction(self.actionFile)
        self.menuDrift_Foraging_Habitat_Suitability.addAction(self.actionLoad_File)
        self.menuDrift_Foraging_Habitat_Suitability.addAction(self.actionQuit)
        self.menubar.addAction(self.menuDrift_Foraging_Habitat_Suitability.menuAction())
        self.menubar.addAction(self.menuMenu_Option_2.menuAction())

        self.retranslateUi(MainWindow)
        self.mainTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Run Model"))
        self.label_12.setText(_translate("MainWindow", "Vertical velocity profile"))
        self.velocityProfile.setItemText(0, _translate("MainWindow", "Uniform"))
        self.velocityProfile.setItemText(1, _translate("MainWindow", "Logarithmic"))
        self.label_2.setText(_translate("MainWindow", "Fish mass"))
        self.label_3.setText(_translate("MainWindow", "g"))
        self.label_4.setText(_translate("MainWindow", "Water temperature"))
        self.label_5.setText(_translate("MainWindow", "°C"))
        self.label_11.setText(_translate("MainWindow", "Swimming cost submodel"))
        self.swimmingCostSubmodel.setItemText(0, _translate("MainWindow", "Brett & Glass 1973 (Sockeye salmon)"))
        self.label.setText(_translate("MainWindow", "Fish focal point depth"))
        self.focalDepthMeaning.setItemText(0, _translate("MainWindow", "as a proportion of water column depth (from 0 to 1)"))
        self.focalDepthMeaning.setItemText(1, _translate("MainWindow", "as a fixed distance above the bottom"))
        self.btnDriftDensityFile.setText(_translate("MainWindow", "Drift density file"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_settings), _translate("MainWindow", "Model Settings"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_results), _translate("MainWindow", "Results"))
        self.btnDepthVelocityFile.setText(_translate("MainWindow", "Depth/velocity file"))
        self.mainTabWidget.setTabText(self.mainTabWidget.indexOf(self.tab_batch), _translate("MainWindow", "Batch Process"))
        self.menuDrift_Foraging_Habitat_Suitability.setTitle(_translate("MainWindow", "BioHSC"))
        self.menuMenu_Option_2.setTitle(_translate("MainWindow", "Menu Option 2"))
        self.actionFile.setText(_translate("MainWindow", "Save File"))
        self.actionLoad_File.setText(_translate("MainWindow", "Load File"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

